[project]
name = "dam-object-extractor"
description = "Extract object names and descriptions from masked regions using NVIDIA's DAM model"
version = "1.0.0"
license = {file = "LICENSE"}
dependencies = ["torch>=2.5.1", "torchvision>=0.20.1", "transformers>=4.51.3", "accelerate>=1.6.0", "numpy>=2.2.5", "pillow>=11.2.1", "opencv-python>=4.11.0", "huggingface-hub>=0.30.2", "safetensors>=0.5.3"]

[project.urls]
Repository = "https://github.com/Irsalistic/comfyui-dam-object-extractor"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = ""
DisplayName = "comfyui-dam-object-extractor"
Icon = ""
